### ISSUE TITLE
Sample Data

### ISSUE THREAD

**Issue by Polewska** [BMD91/webapp22-BuiDuc#1]
I have a question regarding the data that should be displayed in the app. 
Could you provide me with some sample data such as the names of vases or plants and their prices? Or do you have a website or online shop where I could then see those myself?

**Comment by BMD91** [comment]
Sure that, as a client I will write a sample data and you can use it to describe your design.

**Comment by Polewska** [comment]
I have received your sample data via Email, thank you for that. I will use it in a later stage.
