### ISSUE TITLE
Customer ID in Table "Orders"

### ISSUE THREAD

**Issue by Polewska** [BMD91/webapp22-BuiDuc#2]
Since from what I could see we don't have a table with customers, I would suggest that we drop the customer ID and instead replace it with Order ID. That is because in the Table filled with orders we need a key that would differentiate each order from one another, and having Customer as the ID for this Table would mean that 1 customer can't order the plants or vases multiple times.

**Comment by BMD91** [comment]
Agree with your suggestion. Thank you for the advice!
