### ISSUE TITLE
Shimpent

### ISSUE THREAD

**Issue by Polewska** [BMD91/webapp22-BuiDuc#3]
If that would be fine with you I would like to add a column to the "Order" Table called "shipment destination" which would give you the order to where the client wants the plants to be sent. 

Could you tell me if you are selling the plants also in person? I ask this because I want to know if the storage (amount of vases, plants) can also be influenced by in-person purchases. 

If you want me to take care of both in-person and online orders then the "shipment destination" would be optional based on the fact if such order has been placed online or not.

**Comment by BMD91** [comment]
Yes, you can add "Destination" column in your design, and our shop thanks you for that suggestion. 
For online and offline orders, we use same function. So, every order (online or offline) will be calculated in that app. And you can assume that, our shop has unlimited products, so you shouldn't worry about number of each product in our storage. 😁

**Comment by BMD91** [comment]
In our shop we have also a service for shipment. So that customers come and choose, which plants they want. After that we can ship those plants to a place, where our customers want they to be there.

**Comment by Polewska** [comment]
Thank you for your prompt answer. When it comes to the number of plants if that is fine with you I want to try implementing the number of plants and vases in the app. I'm not yet sure if I'm going to be able to do it, but certainly, I can try.

**Comment by BMD91** [comment]
Sure that, your additional part is more than, what we expect. If it will not be successful, don't worry to make the app simple as your original design.
