### ISSUE TITLE
Models

### ISSUE THREAD

**Issue by Polewska** [BMD91/webapp22-BuiDuc#5]
Dear Customer, 

I have uploaded now the domain and design models to README file. If you could please take a look at them and let me know if you accept them?

**Comment by Polewska** [comment]
as you can tell I have added a class called product which summarizes all the plants and vases, as well as a class called Line Item which refers to a single line in the order which shows which product has been bought, their quantity, and their price.

**Comment by BMD91** [comment]
You did really well and that preview is far from what we expect. You can keep your change.
